"""init

Revision ID: 620e9158d592
Revises: 
Create Date: 2026-07-09 18:33:01.535099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620e9158d592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('unique_key', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complaint_type', sa.Text(), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('borough', sa.Enum('MANHATTAN', 'BRONX', 'BROOKLYN', 'QUEENS', 'STATEN ISLAND', name='borough', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('incident_zip', sa.Text(), nullable=True),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unique_key')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index('idx_complaints_borough_created_date', ['borough', 'created_date'], unique=False)
        batch_op.create_index('idx_complaints_complaint_type_created_date', ['complaint_type', 'created_date'], unique=False)
        batch_op.create_index('idx_complaints_created_date', ['created_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('idx_complaints_created_date')
        batch_op.drop_index('idx_complaints_complaint_type_created_date')
        batch_op.drop_index('idx_complaints_borough_created_date')

    op.drop_table('complaints')
    # ### end Alembic commands ###
